apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-demo-page
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <title>Argo CD Learning Lab</title>
      </head>
      <body>
        <h1>GitOps Demo Version 1</h1>
        <p>This page is managed through Git and Argo CD.</p>
      </body>
    </html>
