apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: declarative-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Poomagan/argocd-learning-lab.git
    targetRevision: main
    path: apps/demo

  destination:
    server: https://kubernetes.default.svc
    namespace: declarative-demo

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
